[package]
name = "roughenough"
version = "1.1.0"
repository = "https://github.com/int08h/roughenough"
authors = ["Stuart Stock <stuart@int08h.com>", "Aaron Hill <aa1ronham@gmail.com>"]
license = "Apache-2.0"
description = "A Roughtime secure time sync server and client written in Rust"
readme = "README.md"
keywords = ["roughtime", "cryptography", "crypto"]

[badges]
travis-ci = { repository = "int08h/roughenough", branch = "master" }

[features]
default = []
kms = ["rusoto_core", "rusoto_kms"]

[dependencies]
mio = "0.6"
mio-extras = "2.0"
byteorder = "1"
ring = "0.13"
untrusted = "0.6"
time = "0.1"
log = "0.4"
simple_logger = "0.5"
yaml-rust = "0.3"
ctrlc = { version = "3.1", features = ["termination"] }
clap = "2"
chrono = "0.4"
hex = "0.3"

rusoto_core = { version = "0.34", optional = true }
rusoto_kms = { version = "0.34", optional = true }
